//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentDB
    {
        public AgentDB()
        {
            this.AgentDBSkillDB = new HashSet<AgentDBSkillDB>();
        }
    
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string sex { get; set; }
        public int AgentDBID { get; set; }
        public int aCharacterDBID { get; set; }
        public Nullable<bool> isDead { get; set; }
    
        public virtual CharacterDB CharacterDB { get; set; }
        public virtual ICollection<AgentDBSkillDB> AgentDBSkillDB { get; set; }
    }
}
