//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentDBSkillDB
    {
        public int AgentDBSkillDBID { get; set; }
        public int level { get; set; }
        public int asSkillDBID { get; set; }
        public int asAgentDBID { get; set; }
    
        public virtual AgentDB AgentDB { get; set; }
        public virtual SkillDB SkillDB { get; set; }
    }
}
