//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityDB
    {
        public CityDB()
        {
            this.LocationDB1 = new HashSet<LocationDB>();
        }
    
        public string name { get; set; }
        public Nullable<int> fortificationLevel { get; set; }
        public Nullable<int> fortificationLevelMax { get; set; }
        public int CityDBID { get; set; }
        public Nullable<int> income { get; set; }
        public int cFactionDBID { get; set; }
        public int cLocationDBID { get; set; }
        public Nullable<int> satisfaction { get; set; }
    
        public virtual FactionDB FactionDB { get; set; }
        public virtual LocationDB LocationDB { get; set; }
        public virtual ICollection<LocationDB> LocationDB1 { get; set; }
    }
}
