//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class DialogueDBLetterDB
    {
        public int DialogueDBLetterDBID { get; set; }
        public int dlLetterDBID { get; set; }
        public int dlDialogueDBID { get; set; }
    
        public virtual DialogueDB DialogueDB { get; set; }
        public virtual LetterDB LetterDB { get; set; }
    }
}
