//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDBGoalDB
    {
        public int EventDBGoalDBID { get; set; }
        public Nullable<int> methodId { get; set; }
        public int egGoalDBID { get; set; }
        public int egEventDBID { get; set; }
    
        public virtual EventDB EventDB { get; set; }
        public virtual GoalDB GoalDB { get; set; }
    }
}
