//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDB
    {
        public EventDB()
        {
            this.EventDBGoalDB = new HashSet<EventDBGoalDB>();
            this.RelationModifierDB = new HashSet<RelationModifierDB>();
        }
    
        public string eventDescription { get; set; }
        public Nullable<int> methodID { get; set; }
        public Nullable<int> eventIntensity { get; set; }
        public int EventDBID { get; set; }
        public Nullable<int> resolveTurn { get; set; }
    
        public virtual ICollection<EventDBGoalDB> EventDBGoalDB { get; set; }
        public virtual ICollection<RelationModifierDB> RelationModifierDB { get; set; }
    }
}
