//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactionDB
    {
        public FactionDB()
        {
            this.ArmyDB = new HashSet<ArmyDB>();
            this.CharacterDB = new HashSet<CharacterDB>();
            this.CityDB = new HashSet<CityDB>();
            this.FactionDBLawDB = new HashSet<FactionDBLawDB>();
        }
    
        public string name { get; set; }
        public Nullable<int> gold { get; set; }
        public string emblem { get; set; }
        public int FactionDBID { get; set; }
        public int fFactionGoalID { get; set; }
        public int fCharacterDBID { get; set; }
    
        public virtual ICollection<ArmyDB> ArmyDB { get; set; }
        public virtual ICollection<CharacterDB> CharacterDB { get; set; }
        public virtual CharacterDB CharacterDB1 { get; set; }
        public virtual ICollection<CityDB> CityDB { get; set; }
        public virtual FactionGoalDB FactionGoalDB { get; set; }
        public virtual ICollection<FactionDBLawDB> FactionDBLawDB { get; set; }
    }
}
