//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactionGoalDB
    {
        public FactionGoalDB()
        {
            this.FactionDB = new HashSet<FactionDB>();
        }
    
        public int FactionGoalID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<FactionDB> FactionDB { get; set; }
    }
}
