//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalDB
    {
        public GoalDB()
        {
            this.EventDBGoalDB = new HashSet<EventDBGoalDB>();
        }
    
        public string name { get; set; }
        public int GoalDBID { get; set; }
        public string description { get; set; }
        public int gCharacterDBID { get; set; }
    
        public virtual CharacterDB CharacterDB { get; set; }
        public virtual ICollection<EventDBGoalDB> EventDBGoalDB { get; set; }
    }
}
