//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterDB
    {
        public LetterDB()
        {
            this.CharacterDBLetterDB = new HashSet<CharacterDBLetterDB>();
            this.DialogueDBLetterDB = new HashSet<DialogueDBLetterDB>();
        }
    
        public string finalText { get; set; }
        public int LetterDBID { get; set; }
        public int lCharacterDBID { get; set; }
    
        public virtual CharacterDB CharacterDB { get; set; }
        public virtual ICollection<CharacterDBLetterDB> CharacterDBLetterDB { get; set; }
        public virtual ICollection<DialogueDBLetterDB> DialogueDBLetterDB { get; set; }
    }
}
