//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationDB
    {
        public LocationDB()
        {
            this.ArmyDB = new HashSet<ArmyDB>();
            this.CharacterDB = new HashSet<CharacterDB>();
            this.CityDB = new HashSet<CityDB>();
        }
    
        public string name { get; set; }
        public int LocationDBID { get; set; }
        public Nullable<int> defenderAdvantage { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<ArmyDB> ArmyDB { get; set; }
        public virtual ICollection<CharacterDB> CharacterDB { get; set; }
        public virtual ICollection<CityDB> CityDB { get; set; }
    }
}
