//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationDB
    {
        public OperationDB()
        {
            this.OperationDBSkillDB = new HashSet<OperationDBSkillDB>();
        }
    
        public int OperationDBID { get; set; }
        public Nullable<int> difficulty { get; set; }
        public string description { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> executionTime { get; set; }
        public string name { get; set; }
        public Nullable<int> methodSucessID { get; set; }
        public Nullable<int> methodFailID { get; set; }
    
        public virtual ICollection<OperationDBSkillDB> OperationDBSkillDB { get; set; }
    }
}
