//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationTypeDB
    {
        public RelationTypeDB()
        {
            this.RelationDB = new HashSet<RelationDB>();
        }
    
        public string name { get; set; }
        public string description { get; set; }
        public int RelationTypeDBID { get; set; }
    
        public virtual ICollection<RelationDB> RelationDB { get; set; }
    }
}
