//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationModifierDB
    {
        public Nullable<int> modifierValue { get; set; }
        public string shortDescription { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public int RelationModifierDBID { get; set; }
        public int rmRelationDBID { get; set; }
        public int rmEventDBID { get; set; }
    
        public virtual EventDB EventDB { get; set; }
        public virtual RelationDB RelationDB { get; set; }
    }
}
