//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theasian_Diplomacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillDB
    {
        public SkillDB()
        {
            this.AgentDBSkillDB = new HashSet<AgentDBSkillDB>();
            this.CharacterDBSkillDB = new HashSet<CharacterDBSkillDB>();
            this.OperationDBSkillDB = new HashSet<OperationDBSkillDB>();
        }
    
        public int SkillDBID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<AgentDBSkillDB> AgentDBSkillDB { get; set; }
        public virtual ICollection<CharacterDBSkillDB> CharacterDBSkillDB { get; set; }
        public virtual ICollection<OperationDBSkillDB> OperationDBSkillDB { get; set; }
    }
}
